#!/bin/bash

### BEGIN INIT INFO
# Provides:          Greekify.herm
# Required-Start:    $local_fs $remote_fs $network $time
# Required-Stop:     $local_fs $remote_fs $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Encrypted File Observer
# Description:       Takes a directory as an arguement and 
#                    inserts an encrypted file into it to
#                    be monitored for changes.  
### END INIT INFO

target= #insert directory here

. /lib/lsb/init-functions

NAME=greekify_daemon

#set location of daemon executable
DAEMON=/home/Documents/checksumTest

#set pid file for daemon
PIDFILE=/var/run/greekify_daemon.pid

#test for daemon
test -x $DAEMON || exit 5

case $1 in start) 
  if [ -e $PIDFILE ]; then
    status_of_proc -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
    if [ $status = "0" ]; then
      exit 
    fi
  fi

log_daemon_msg "Starting the process" "$NAME"

if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON ; then 
  log_end_msg 0
else
  log_end_msg 1
fi 
;; stop)
